### ISSUE TITLE
Tutorial Correction

### ISSUE THREAD

**Issue by vodelerk** [hashicorp/learn-terraform-advanced-deployments#1]
in this tutorial: https://learn.hashicorp.com/tutorials/terraform/blue-green-canary-tests-deployments?in=terraform/aws
in section: Add feature toggles to route traffic

it says: "The green-90 target distribution increases traffic to the green environment — 90% of the traffic is routed to the blue environment, 10% to the green environment."

if you check the locals in variables.tf:
green-90 = {
      blue  = 10
      green = 90
}

I think there is an error, the correct way, would be "The green-90 target distribution increases traffic to the green environment — 90% of the traffic is routed to the green environment, 10% to the blue environment."

thanks,

**Comment by im2nguyen** [comment]
Nice catch, updating now! 😄
