### ISSUE TITLE
Module content correction

### ISSUE THREAD

**Issue by JamesFromIT** [hashicorp/learn-terraform-advanced-deployments#3]
Under the "Deploy green environment" heading at https://developer.hashicorp.com/terraform/tutorials/aws/blue-green-canary-tests-deployments.

The script is referenced as `/init-script.sh.tftpl`, I think this should be `/init-script.sh`. Otherwise the code will fail on `terriform apply` with the error message below:

```
Invalid value for "path" parameter: no file exists at
"./init-script.sh.tftpl"; this function works only with files     
that are distributed as part of the configuration source code, so 
if this file will be created by a resource in this configuration  
you must instead obtain this result from an attribute of that     
resource.
```

**Comment by ritsok** [comment]
fixing, thank you!
