### ISSUE TITLE
Text duplication in guide

### ISSUE THREAD

**Issue by JamesFromIT** [hashicorp/learn-terraform-advanced-deployments#4]
It seems above the last code block in the "Add feature toggles to route traffic" section (https://developer.hashicorp.com/terraform/tutorials/aws/blue-green-canary-tests-deployments). Two sentences are repeated but slightly reworded.

> Replace the aws_lb_listener.app default action block in main.tf. The configuration uses [lookup](https://developer.hashicorp.com/terraform/docs/language/functions/lookup) to set the target groups' weight. Notice that the configuration defaults to a directing all traffic to the blue environment if no value is set.

> Modify the aws_lb_listener.app's default action block in main.tf to match the following. The configuration uses [lookup](https://developer.hashicorp.com/terraform/docs/language/functions/lookup) to set the target groups' weight. Notice that the configuration defaults to a directing all traffic to the blue environment if no value is set.

**Comment by ritsok** [comment]
thank you!
