### ISSUE TITLE
Sentence mistake

### ISSUE THREAD

**Issue by JamesFromIT** [hashicorp/learn-terraform-advanced-deployments#5]
Under the "Start shifting traffic to blue environment" heading, it says "Once the apply completes, Verify that your load balancer is routing all traffic to the green environment." But at this point in the tutorial we aren't routing all traffic to the green environment, only 90% of it.

https://developer.hashicorp.com/terraform/tutorials/aws/blue-green-canary-tests-deployments

**Comment by ritsok** [comment]
Updating the tutorial to reflect this, thanks for the catch!
